### ISSUE TITLE
Columns returned in Get-ServiceNowTable not returned in the order requested

### ISSUE THREAD

**Issue by Bruce915** [Sam-Martin/servicenow-powershell#101]
When I call Get-ServiceNowTable and specify -Query with the set of column names the columns do not return in the order I specified.  So I have to then do a Select to get them in the order I want.  Is this a limitation of the API itself?

Get-ServiceNowTable -Table $snowTableName -Limit 10000 -Properties $cols | select $cols | Export-Csv -Path $csvFileName 

Thanks, Bruce...

**Comment by Rick-2CA** [comment]
The API doesn't have any features that allow for the returned data have properties sorted for us.
