### ISSUE TITLE
Create Service Requests 

### ISSUE THREAD

**Issue by arunsk7891** [Sam-Martin/servicenow-powershell#115]
Hello Team 
You have a great repo here . 

Please guide How can I create Service Requests using the Wrapper . - tickets which are like  REQ0012958 
Requesting to please help ASAP - I'm stuck and im new here 
any guidance will be greatly appreciable  .
Kind regards
Arun 
arunsk7891@gmail.com

**Comment by arunsk7891** [comment]
@Rick-2CA  - Requesting you help guidance here  .

**Comment by Rick-2CA** [comment]
Please see #102 for comments on service requests.
