### ISSUE TITLE
Module Rename

### ISSUE THREAD

**Issue by Rick-2CA** [Sam-Martin/servicenow-powershell#17]
Work has been staged for a module rename to fall into accordance with module naming standards as communicated with Issue #1.  This brings up a challenge:

The PowerShell Gallery works by module name.  A module rename means a new gallery entry.  Microsoft recommends uploading under the new name and then unlisting the versions under the old name.  There is no method of redirection available.  Removing the listings has more to do with trying to get people onto the latest supported version instead of the older code than anything.

I worry a little about abandoning people that may rely upon updating via the console only.  I have plenty of modules where I only update when I see a new version with Find-Module.  To aid on this topic I've considered an update under the old name that would stay listed on the Gallery (for a period of time?) that would add a message to the console advertising the new name/version.

Any thoughts on those steps?

**Comment by Sam-Martin** [comment]
@Rick-2CA  I vote we do a final version of PSServiceNow which throws a `write-warning` at the beginning of each cmdlet advising that it has been renamed and that users should look to the new module for the latest updates.

**Comment by Rick-2CA** [comment]
That'll work, thank you.

Good luck to you guys with today's events.  Hope everyone around you is safe.

**Comment by Rick-2CA** [comment]
Added a new branch today to do the last update of the current version.  I don't intend on merging it into master, but rather publishing and abandoning the code.  It won't be published until the new version is ready to go so the message can be finalized.

Along with the warning message in the main psm1 I added a line to Set-ServiceNowAuth that is set to $null.  For some reason that one function wasn't triggering the warning, but making it call another function in the main psm1 consistently triggered it.  Mystery to me if anyone knows why it might behave like that.  No other function in the same psm1 behaved that way.

**Comment by Rick-2CA** [comment]
@Sam-Martin - Trying to step closer to making this happen...

I'm proposing calling the current dev version 2.0 and merging it into master.
Once there I'll publish under the new name to the PSGallery and set you as an owner.
I'll then publish the last update of v1 to the PSGallery and hide that option from the gallery search.

Do we want to address any of this in the readme.md?  Do we need a link to "Why there's a version 2" with a summary and the short list of changes that were completed?

Anything else I ought to do that I'm overlooking?

**Comment by Sam-Martin** [comment]
@Rick-2CA that sounds good to me. I would suggest addressing the psservicenow vs servicenow question as a top level item and mentioning v2.0 in that.

Many thanks,

Sam

**Comment by Rick-2CA** [comment]
ReadMe updated in dev branch.  Will make a second pass and likely merge things this week and then work on the PSGallery deployments sometime after that.  I hope...

**Comment by Rick-2CA** [comment]
@Sam-Martin - Was chatting about versioning with a gentleman in the PowerShell Slack channel.  Any sense in taking the current v0.1.13 (published) version and calling the next version a v1 instead of my earlier proposed v2?  The majority of changes are back end and thus don't break the module.  That leaves feature additions and the rename.  The rename isn't breaking the old stuff either, it's just a fresh start with a new name.  What say you?

**Comment by Sam-Martin** [comment]
Hey @Rick-2CA . v1 sounds fine to me! So long as the `major` number in the semantic versioning gets incremented, I don't mind 😄

**Comment by Rick-2CA** [comment]
v1.0.0 updated in Master and published with PR #21.
