### ISSUE TITLE
/api/now/v1 doesn't work for me

### ISSUE THREAD

**Issue by codykonior** [Sam-Martin/servicenow-powershell#18]
Heya,

Just wanted to let you know that for some reason on my SNOW instance having the /v1 at the end of the PSServiceNow.psm1 Set-ServiceNowAuth stops it from working. Removing the /v1 makes it work.

Cheers

**Comment by Rick-2CA** [comment]
Curious.  What release of ServiceNow do you use?  I haven't dug too far to see if there is alternate documentation, but the /v1 documentation is what I've run into, what Sam built originally, and it works in a variety of Helsinki builds I've used as well as Jakarta builds on the ServiceNow dev site.
