### ISSUE TITLE
Domain name set to https

### ISSUE THREAD

**Issue by onkarshinde** [Sam-Martin/servicenow-powershell#48]
I use Set-ServiceNowAuth and use example.com (without http or https). When I call Get-ServiceNowIncident I get error domain not resolved 'https'.
I had to remove 'https://' from below line in Get-ServiceNowTable.ps1
`$ServiceNowURL = 'https://' + $ServiceNowURL + '/api/now/v1'`

**Comment by Rick-2CA** [comment]
@onkarshinde - Any updates on your issue?

**Comment by onkarshinde** [comment]
If I remember correctly all I did was do Set-ServiceNowAuth command followed by Get-ServiceNowIncident. I don't currently have access to the system where I faced this issue. Give mew few days and I will try to provide exact steps.
