### ISSUE TITLE
Web Proxy configuration fork

### ISSUE THREAD

**Issue by amandadebler** [Sam-Martin/servicenow-powershell#7]
Hi, @Sam-Martin - thanks for putting this module out there. It helped me figure out how to connect to ServiceNow. Since the main thing missing from it for me is the -Proxy parameter in Invoke-RestMethod, I've just now started a fork to make that convenient: https://github.com/amandadebler/servicenow-powershell

(Announcing that here, in case anyone else is dealing with a web proxy that requires authentication)

**Comment by Sam-Martin** [comment]
Hi @amandadebler,
Awesome! Thanks for patching it in. Do you fancy submitting a pull-request to add it back into this repo so it can be published on the PowerShell gallery?

Thanks,

Sam

**Comment by amandadebler** [comment]
Once it gets to a generally-useful state, sure!
