### ISSUE TITLE
Get-ServiceNowIncident with sys_created_on

### ISSUE THREAD

**Issue by jbruns2019** [Sam-Martin/servicenow-powershell#94]
Is there a way to request only incidents created on or after a certain date?

Was thinking that -MatchExact could be used with some sort of greater than or equal to thing.

**Comment by Rick-2CA** [comment]
#68 covers this topic.  The module doesn't support this feature today.  

```
active=true^state!=6^sys_created_onBETWEENjavascript:gs.dateGenerate('2016-10-01','00:00:00')@javascript:gs.dateGenerate('2016-12-01','23:59:59')
```
That's an example format of what the query string needs to look like if you were to attempt to integrate it into what you need manually.  At least until we get time to plan out an integration that makes sense for the module.
