### ISSUE TITLE
Getting the Sys_Id information on an already existing service now incident

### ISSUE THREAD

**Issue by ghost** [Sam-Martin/servicenow-powershell#95]
Hello, is there an existing way to grab the sys_id for an already existing ticket/incident number in service now? What I am trying to do is update an incident which wasn't created by the service now module, but I can't find a way to grab the sys_id without actually creating a ticket using your module.

**Comment by Rick-2CA** [comment]
![image](https://user-images.githubusercontent.com/25209634/66507300-935e4900-ea94-11e9-992c-e0dbd713fcb4.png)

You query for the ticket and the data returned includes sys_id.

**Comment by kdrumz23** [comment]
What would a query look like to return the sys_id if I already know the ticket/incident number?

**Comment by Rick-2CA** [comment]
You'd do  `Get-ServiceNowIncident -MatchExact @{number='INC0123456'}` to get the number you want.  You could add `-Properties sys_id` to only pull back the sys_id if you want (or any specific list of properties).  Otherwise it'll pull back default values.

Or for what you described you can take advantage of `Update-ServiceNowNumber` by passing the number and table and let it look up the sys_id for you by doing  `Update-ServiceNowNumber -Number INC0123456 -Table incident -Values @{property='value'}`.

**Comment by kdrumz23** [comment]
so the command `Get-ServiceNowIncident -MatchExact @{number='ticket_number'}` works for querying the sys_id for tickets created using your service now module. But when I try to query a ticket_number which was created from the web interface of service now, nothing is returning... Any idea what could be happening? Thank you

**Comment by Rick-2CA** [comment]
The PowerShell module interacts with the ServiceNow database just like the web interface does.  What you may be running into is the type of ticket you're searching for.  `Get-ServiceNowIncident` queries the `incident` database specifically.  That's a ticket with a number that begins with `INC`.  If you're trying to find a different ticket type you'd need to use the corresponding command.  If that command doesn't exist you'd want to use `Get-ServiceNowTableEntry` and specify the table name that has your ticket.  That's how you'd query for custom ticket tables for example.

**Comment by kdrumz23** [comment]
I'm still trying to query an incident, just not created with the powershell module and instead from the web interface. Is it possible that when I create a ticket from the web interface that the ticket is being stored under a different table other than `incident`? I'm not sure what else to try...

**Comment by Rick-2CA** [comment]
If you open the ticket in the web you should get a URL such as `https://iheartmedia.service-now.com/nav_to.do?uri=%2Fsc_req_item.do%3` and be able to see which table you're looking at.  In this example my URL shows me in the `sc_req_item` table.  Could help you confirm which database you're working in.  It should be the incident table from what you described.
