### ISSUE TITLE
Is this module tested and certified for Powershell Core 6.0? 

### ISSUE THREAD

**Issue by iogbole** [Sam-Martin/servicenow-powershell#99]

**Comment by Rick-2CA** [comment]
The module is NOT tested or certified for Core.  There is functionality, but I can't comment on what doesn't work or if anything works at all on a non-Windows machine at this time.

**Comment by iogbole** [comment]
Thanks for your response @Rick-2CA . You will be happy to know that it works great from macOS and centOS. Thank for putting this together!
